openapi: 3.0.0

info:
  title: Wasapp Service API Documentation
  description: |
    API for interacting with Wasapp, a messaging service.
  version: 1.0.0

# ================================================================

paths:

  # -------------------- LOGIN --------------------
  /session:
    post:
      tags: ["login", "user-management"]
      summary: Log in a user
      description: |
        If the user does not exist, a new user will be created and both the user identifier and an authentication token will be returned.
        If the user already exists, the user identifier and an authentication token will be returned.
      operationId: doLogin
      security: []    # This operation does not require authentication
      requestBody:
        description: User details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        '201':
          description: User created and logged in successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        '400':
          description: Bad request – invalid username.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  # -------------------- USERNAME UPDATE --------------------
  /users/{userID}/username:
    parameters:
      - $ref: '#/components/parameters/UserID'
      
    patch:
      tags: ["user-management"]
      summary: Update user's username
      operationId: setMyUserName
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  $ref: '#/components/schemas/UserName'
      responses:
        "200":
          description: Username updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: Invalid username (too short or too long or invalid chars).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "401":
          description: Authentication required or failed.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "403":
          description: Forbidden — You can only change your own username, not another user's.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "404":
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "409":
          description: Username already in use.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


# ================================================================

# By default, all operations require authentication.
# Add "security: []" to an operation to specify that it does not require authentication
security:
  - BearerAuth: []

components:
  parameters:
    UserID:
      name: userID
      in: path
      description: A user's unique identifier.
      required: true
      schema: { $ref: '#/components/schemas/UserID' }
  
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: "JWT"

  # ================================================================

  schemas:
    # -------------------- BASE COMPONENTS --------------------
    # Basic components used in various schemas
    
    BaseID:
      type: string
      format: uuid
      readOnly: true
      example: "550e8400-e29b-41d4-a716-446655440000"

    BaseName:
      type: string
      pattern: '^[A-Za-z0-9]+$'
      minLength: 3
      maxLength: 16

    # -------------------- USER -------------------- 
    User:
      type: object
      description: Represents a user of the platform.
      required: [userID, userName]
      properties:
        userID:     { $ref: '#/components/schemas/UserID' }
        userName:   { $ref: '#/components/schemas/UserName' }

    UserID:
      allOf:
        - $ref: '#/components/schemas/BaseID'
        - description: Unique identifier assigned to the user by the server.

    UserName:
      allOf:
        - $ref: '#/components/schemas/BaseName'
        - description: Unique username visible to other users.
        - example: Feldspar 
    
    # -------------------- LOGIN --------------------
    LoginRequest:
      type: object
      required: [userName]
      properties:
        userName: { $ref: '#/components/schemas/UserName' }

    BearerToken:
      description: |
        Token used to fullfil the Bearer Authentication standard.
      type: string
      pattern: ^Bearer\s[A-Za-z0-9-._~+/]+={0,2}$
      example: Bearer JhdkEN7QWidlYDjRTH8I~n99YJfqCC==

    AuthResponse:
      type: object
      readOnly: true
      properties:
        identifier:
          { $ref: "#/components/schemas/UserID" }
        token:
          { $ref: "#/components/schemas/BearerToken" }

    # -------------------- ERRORS --------------------
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required: [code, message]